### ISSUE TITLE
Cannot parse/get correct data from Techcrunch blog posts

### ISSUE THREAD

**Issue by ryzalyusoff** [metainspector/metainspector#259]
I am having trouble parsing and getting correct infos from Techcrunch blog posts. Take a look at these links for example:
1) [https://techcrunch.com/2020/04/01/take-your-shot-apply-to-tc-top-picks-at-disrupt-sf-2020/](url)
2) [https://techcrunch.com/2019/09/30/spacex-details-starship-and-super-heavy-in-new-website/](url)

And instead of getting the correct title and description etc, heres the response that I got:

**Title:** "TechCrunch is now a part of Verizon Media"
**Description:** "TechCrunch is part of Verizon Media. Click 'I agree' to allow Verizon Media and our partners to use cookies and similar technologies to access your device and use your data (including location) to understand your interests, and provide and measure personalised ads. We will also provide you with personalised ads on partner products.\n                         Learn more about how we use your data in our Privacy Centre. Once you confirm your privacy choices here, you can make changes at any time by visiting your Privacy dashboard."

![Screen Shot 2020-04-01 at 18 03 21](https://user-images.githubusercontent.com/735775/78165376-24f6b400-7443-11ea-80c6-9599f0ecb56a.png)

**Comment by jaimeiniesta** [comment]
Yes, it looks like TechCrunch wants you to accept some cookies in order to see the content. If I visit those URLs in my browser I see a pop-up asking me to accept the cookies.

And if I use curl to get the contents (which is similar to what MetaInspector does), I see a `307 Temporary Redirect` due to cookies not being accepted:

```
➔ curl -i https://techcrunch.com/2020/04/01/take-your-shot-apply-to-tc-top-picks-at-disrupt-sf-2020/
HTTP/2 307
date: Thu, 02 Apr 2020 12:26:17 GMT
ec-policy-id: 104206
location: https://guce.techcrunch.com/consent?brandType=nonEU&done=https%3A%2F%2Ftechcrunch%2Ecom%2F2020%2F04%2F01%2Ftake%2Dyour%2Dshot%2Dapply%2Dto%2Dtc%2Dtop%2Dpicks%2Dat%2Ddisrupt%2Dsf%2D2020%2F&gcrumb=k1I87ms=
server: ECAcc (mic/9BB3)
set-cookie: GUCS=AZNSPO5r; Domain=.techcrunch.com; Max-Age=1800; Path=/; Secure
x-ec-guce: guce-or-acookie-missing
content-length: 0
```

MetaInspector is going to follow these redirections, if you have a look at `page.url` you'll see the final URL, which is the one the title and description is being taking from, something like:

`"https://consent.yahoo.com/collectConsent?sessionId=3_cc-session_6cccd599-c37f-4874-b76a-ac8f5b60a94d&lang=&inline=false"`

There's not much we can do with MetaInspector in order to accept the cookies I'm afraid.

**Comment by kalemi19** [comment]
Try using a proxy. That did the trick for us. We're currently using NordVPN (US server) and you can pass the proxy info to the faraday_options as the following

```
page = MetaInspector.new(url, faraday_options: { proxy: "https://#{URI.escape(ENV['PROXY_USER'], '@')}:#{ENV['PROXY_PASSWORD']}@#{ENV['PROXY_ADDRESS']}:80" })
```
