### ISSUE TITLE
Failed to fetch correct best title from URL with double quotes characters title

### ISSUE THREAD

**Issue by gizipp** [metainspector/metainspector#262]
Hello, @jaimeiniesta 

The URL below has quotation marks in the title, thus the value of meta twitter:title seems incorrect. 

URL : https://cobwwweb.com/add-reload-method-to-ruby-console
Title : Add a "reload!" Method to your Ruby Console
Best Title: Add a

Checked using web also failed https://metainspectordemo.herokuapp.com/scrape?url=https%3A%2F%2Fcobwwweb.com%2Fadd-reload-method-to-ruby-console

Cannot tell if is bug from MetaInspector or Nokogiri.

**Comment by jschwindt** [comment]
@gizipp The problem is that the HTML es malformed because the quotes must be escaped and in this case they aren’t:

`<meta name="twitter:title" content="Add a "reload!" Method to your Ruby Console">`

The HTML should be this way:

`<meta name="twitter:title" content="Add a &quot;reload!&quot; Method to your Ruby Console">`

Check this: https://validator.w3.org/nu/?doc=https%3A%2F%2Fcobwwweb.com%2Fadd-reload-method-to-ruby-console
